# Generated by Django 5.1.4 on 2025-02-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
