# Generated by Django 5.1.4 on 2025-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
