# Generated by Django 5.1.4 on 2025-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='avatar',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
