# Generated by Django 5.1.4 on 2025-02-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='avatar',
        ),
    ]
