# Generated by Django 5.1.4 on 2025-02-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_ticket_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
