# Generated by Django 5.1.4 on 2025-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_ticket_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='github',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.IntegerField(unique=True),
        ),
    ]
